# Generated by Django 3.0.7 on 2020-06-25 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('image', models.ImageField(default='author/default-img.png', upload_to='author/img/')),
                ('bio', models.TextField(max_length=500)),
                ('facebook_URL', models.URLField(blank=True, null=True)),
                ('twitter_URL', models.URLField(blank=True, null=True)),
                ('linkedin_URL', models.URLField(blank=True, null=True)),
                ('activated_account', models.BooleanField(default=False)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(default='no-img.png', upload_to='img/')),
                ('post_body', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Approved'), (2, 'Rejected'), (3, 'Archived')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LVR.blog_author')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='blog_postComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=125)),
                ('author_email', models.EmailField(max_length=254)),
                ('comment_body', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('has_report', models.BooleanField(default=False)),
                ('in_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='LVR.blog_post')),
            ],
        ),
    ]
