# Generated by Django 3.0.7 on 2020-06-28 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LVR', '0003_auto_20200628_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='category',
            field=models.ForeignKey(default='Uncategorized', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='LVR.blog_category'),
        ),
    ]
