# Generated by Django 3.0.7 on 2020-06-29 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LVR', '0004_auto_20200628_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='category',
            field=models.ForeignKey(default='Uncategorized', on_delete=django.db.models.deletion.CASCADE, related_name='catego', to='LVR.blog_category'),
        ),
    ]
