# Generated by Django 3.0.7 on 2020-07-01 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LVR', '0005_auto_20200629_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_misc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('head_desc', models.CharField(max_length=200)),
                ('bgImage', models.URLField(max_length=500)),
                ('content', models.TextField()),
            ],
        ),
    ]
