# Generated by Django 3.0.7 on 2020-07-03 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LVR', '0006_blog_misc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='catego', to='LVR.blog_category'),
        ),
        migrations.AlterField(
            model_name='blog_postcomment',
            name='in_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='LVR.blog_post'),
        ),
    ]
