# Generated by Django 3.0.7 on 2020-07-03 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LVR', '0011_auto_20200703_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_postcomment',
            name='in_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='LVR.blog_post'),
        ),
    ]
