# Generated by Django 3.0.7 on 2020-07-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVR', '0013_blog_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=35)),
                ('image', models.ImageField(default='crew/default-img.png', upload_to='crew/img/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('facebook_URL', models.URLField(blank=True, null=True)),
                ('instagram_URL', models.URLField(blank=True, null=True)),
                ('twitter_URL', models.URLField(blank=True, null=True)),
                ('linkedin_URL', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
