# Generated by Django 3.0.7 on 2020-08-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVR', '0015_auto_20200807_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
