# Generated by Django 3.0.7 on 2020-08-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVR', '0016_auto_20200807_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='unsplash_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
