# Generated by Django 3.0.7 on 2020-08-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVR', '0017_blog_post_unsplash_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='vote_fav',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='vote_tmbdn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='vote_tmbup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='vote_util',
            field=models.IntegerField(default=0),
        ),
    ]
