# Generated by Django 3.0.7 on 2020-08-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LVR', '0018_auto_20200807_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='send_to_newsletter',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
